name: Publish

on:
  push:
    branch:
      - main
    paths:
      - apps/**

jobs:
  deployment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [cruncher]
    steps:
      - name: GitHub Tag
        uses: mathieudutour/github-tag-action@v6.1
