name: Publish

on:
  push:
    branch:
      - main
    paths:
      - apps/**
  pull_request:
    branch:
      - main
    paths:
      - apps/**

jobs:
  deployment:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        app: [cruncher]
    steps:
      # Always checkout latest commit
      - uses: actions/checkout@v4
      # Tag version to easily see deployed version
      - name: GitHub Tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          # Follow Golang tagging for mono repos
          tag_prefix: apps/${{ matrix.app }}/v
          # Make sure the latest of a specific tag is always found
          fetch_all_tags: true

      - name: Build image
        run: docker build -t ${{ matrix.app }} .
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Push image
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/${{ matrix.app }}
          VERSION=${{ steps.tag.outputs.new_version }}
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker tag $IMAGE_NAME $IMAGE_ID:latest
          docker push --all-tags $IMAGE_ID
