name: Checks

on:
  push:
    branches:
      - main
    paths:
      - "apps/**"
  pull_request:
    branches:
      - main
    paths:
      - "apps/**"

jobs:
  build-scan:
    name: Build & Scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: go

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:go"

  pre-checks:
    name: Pre-Checks
    runs-on: ubuntu-latest
    needs: [build-scan]
    steps:
      - name: All checks successful
        if: contains(needs.*.result,'success')
        run: echo "success!"
